/**
 * All editable copy lives here (plus the static English baked into index.html —
 * keep the two in sync when you edit; see README "Editing content").
 *
 * ASSUMPTION LOG (see NOTES.md):
 * - The 6 "Why Innova" points and per-service package names paraphrase the brief;
 *   swap in the official site copy when available.
 * - "Explore" URLs default to the homepage — replace with real service-page URLs.
 */

export type Lang = 'en' | 'ar';

export interface ServiceDef {
  id: string;
  /** world scene key rendered when diving through this portal */
  world:
    | 'contracting' | 'pm' | 'facility' | 'cinema' | 'snagging'
    | 'marketing' | 'consultancy' | 'ai' | 'homewatch';
  /** TODO: replace with the real service page URL on innovagroup.co.ae */
  url: string;
  soon?: boolean;
}

export const CONTACT_URL = 'https://innovagroup.co.ae/contact/';
export const WHATSAPP_URL = 'https://wa.me/971505097758';
export const PHONE = '+971505097758';

export const SERVICES: ServiceDef[] = [
  { id: 'contracting', world: 'contracting', url: 'https://innovagroup.co.ae/' },
  { id: 'pm', world: 'pm', url: 'https://innovagroup.co.ae/' },
  { id: 'facility', world: 'facility', url: 'https://innovagroup.co.ae/' },
  { id: 'cinema', world: 'cinema', url: 'https://innovagroup.co.ae/' },
  { id: 'snagging', world: 'snagging', url: 'https://innovagroup.co.ae/' },
  { id: 'marketing', world: 'marketing', url: 'https://innovagroup.co.ae/' },
  { id: 'consultancy', world: 'consultancy', url: 'https://innovagroup.co.ae/' },
  { id: 'ai', world: 'ai', url: 'https://innovagroup.co.ae/' },
  { id: 'homewatch', world: 'homewatch', url: CONTACT_URL, soon: true },
];

type Dict = Record<string, string>;

const en: Dict = {
  'ui.skip': 'Skip to content',
  'ui.sound': 'Sound',
  'ui.menu': 'Menu',
  'ui.scroll': 'Scroll',
  'ui.enterWorld': 'Step inside',
  'ui.explore': 'Explore the service',
  'ui.comingSoon': 'Coming soon',
  'ui.notify': 'Ask about launch',
  'nav.services': 'Services',
  'nav.why': 'Why Innova',
  'nav.process': 'How we work',
  'nav.enquire': 'Enquire',
  'hero.kicker': 'Innova Group LLC · Meydan, Dubai',
  'hero.title': 'We build it, we run it, and we make it smarter.',
  'hero.lede': 'Build. Manage. Innovate. Eight service lines under one licensed team — and one point of accountability.',
  'cta.enquire': 'Start an enquiry',
  'cta.whatsapp': 'WhatsApp us',
  'cta.call': 'Call +971 50 509 7758',
  'cta.title': 'Tell us what you’re planning.',
  'cta.lede': 'A villa, a tower, a cinema, a smarter business — start the conversation and we’ll take it from there.',
  'gaps.title': 'Most projects don’t fail on site. They fail in the gaps.',
  'gaps.lede': 'Between the contractor and the consultant. Between handover and operations. Innova exists to close them — one team, accountable for the whole.',
  'orbit.title': 'One diamond. Nine facets.',
  'orbit.lede': 'Every facet is a service — and behind each one, the same team answers.',
  'orbit.hint': 'Drag to spin the ring · click a portal to step inside',
  'svc.contracting.name': 'Turnkey Contracting',
  'svc.contracting.short': 'Contracting',
  'svc.contracting.tag': 'From shell to signature.',
  'svc.contracting.desc': 'Design, build and finish under one contract. A raw structure becomes a finished, working space — without you chasing ten companies.',
  'svc.contracting.pack': 'Fit-out · Renovation · New build',
  'svc.pm.name': 'Project Management',
  'svc.pm.short': 'Projects',
  'svc.pm.tag': 'Your side of the table.',
  'svc.pm.desc': 'Planning, tendering, supervision and reporting. We stand for your interests from the first drawing to the final snag.',
  'svc.pm.pack': 'Owner’s representative · Design management · Site supervision',
  'svc.facility.name': 'Maintenance & Facility Management',
  'svc.facility.short': 'Facility',
  'svc.facility.tag': 'Buildings that never sleep.',
  'svc.facility.desc': 'Planned and reactive maintenance, MEP care and facility operations that keep your property performing around the clock.',
  'svc.facility.pack': 'Annual contracts · On-call maintenance · Full facility operation',
  'svc.cinema.name': 'Cinema & Home Theatre',
  'svc.cinema.short': 'Cinema',
  'svc.cinema.tag': 'Your private premiere.',
  'svc.cinema.desc': 'Acoustics, calibrated picture and sound, seating and control — private cinemas designed, built and tuned end to end.',
  'svc.cinema.pack': 'Media room · Dedicated cinema · Reference grade',
  'svc.snagging.name': 'Snagging',
  'svc.snagging.short': 'Snagging',
  'svc.snagging.tag': 'We see what others miss.',
  'svc.snagging.desc': 'Independent handover inspections with a defect report your developer can act on — before you sign.',
  'svc.snagging.pack': 'Apartment · Villa · Re-inspection',
  'svc.marketing.name': 'Marketing, PR & Communication',
  'svc.marketing.short': 'Marketing',
  'svc.marketing.tag': 'Make it unmissable.',
  'svc.marketing.desc': 'Brand, content and communication that carry your name further — built and run by one accountable team.',
  'svc.marketing.pack': 'Brand & identity · Campaigns · Ongoing communication',
  'svc.consultancy.name': 'Management Consultancies',
  'svc.consultancy.short': 'Consultancy',
  'svc.consultancy.tag': 'Order out of moving parts.',
  'svc.consultancy.desc': 'Structure, process and governance for growing businesses — practical advice that lands in operations, not just in slides.',
  'svc.consultancy.pack': 'Diagnosis · Operating model · Implementation',
  'svc.ai.name': 'AI Research & Consultancy',
  'svc.ai.short': 'AI',
  'svc.ai.tag': 'Make it smarter.',
  'svc.ai.desc': 'Applied AI research, automation and advisory — we find where intelligence saves you time and money, then we build it.',
  'svc.ai.pack': 'AI readiness · Pilots · Deployment & training',
  'svc.homewatch.name': 'Home Watch & Property Concierge',
  'svc.homewatch.short': 'Home Watch',
  'svc.homewatch.tag': 'Watched over, always.',
  'svc.homewatch.desc': 'Regular inspections, guest readiness and concierge care for your villa while you’re away. Launching soon.',
  'svc.homewatch.pack': 'Watch visits · Arrival prep · Concierge on demand',
  'why.title': 'Fewer parties. Clearer answers.',
  'why.p1.t': 'One accountable partner',
  'why.p1.d': 'Design, build and operations under a single agreement — one call when you need an answer.',
  'why.p2.t': 'Licensed, multi-disciplinary',
  'why.p2.d': 'A licensed company in Meydan, Dubai, with the trades and specialists in-house.',
  'why.p3.t': 'No finger-pointing',
  'why.p3.d': 'When one team owns the whole scope, there is no gap for problems to hide in.',
  'why.p4.t': 'Continuity',
  'why.p4.d': 'The people who built your space stay to run and maintain it.',
  'why.p5.t': 'Transparent scope',
  'why.p5.d': 'Clear scope, timelines and reporting — you always know where your project stands.',
  'why.p6.t': 'Smarter by design',
  'why.p6.d': 'AI and automation applied where they genuinely save you time and money.',
  'process.title': 'How we work',
  'process.s1.t': 'Listen',
  'process.s1.d': 'We start with your goals, constraints and the realities of your site.',
  'process.s2.t': 'Scope',
  'process.s2.d': 'A clear scope, timeline and one accountable owner — agreed before work begins.',
  'process.s3.t': 'Deliver',
  'process.s3.d': 'Licensed teams execute. One call, no gaps, no surprises.',
  'process.s4.t': 'Support',
  'process.s4.d': 'We stay after handover — maintenance, care and upgrades.',
  'contact.addr': 'Meydan, Dubai, United Arab Emirates',
  'footer.tag': 'Build. Manage. Innovate.',
  'footer.soon': 'Home Watch & Property Concierge — coming soon.',
  'sticky.call': 'Call',
  'sticky.enquire': 'Enquire',
  'loader.preparing': 'Preparing the diamond',
  'loader.enterSound': 'Enter with sound',
  'loader.enterQuiet': 'Enter in silence',
  'world.return': 'Back to the diamond',
  'world.prev': 'Previous service',
  'world.next': 'Next service',
};

const ar: Dict = {
  'ui.skip': 'تخطَّ إلى المحتوى',
  'ui.sound': 'الصوت',
  'ui.menu': 'القائمة',
  'ui.scroll': 'مرّر',
  'ui.enterWorld': 'ادخل العالم',
  'ui.explore': 'اكتشف الخدمة',
  'ui.comingSoon': 'قريباً',
  'ui.notify': 'اسأل عن الإطلاق',
  'nav.services': 'خدماتنا',
  'nav.why': 'لماذا إنوفا',
  'nav.process': 'كيف نعمل',
  'nav.enquire': 'استفسر',
  'hero.kicker': 'إنوفا جروب ذ.م.م · ميدان، دبي',
  'hero.title': 'نبنيها، نديرها، ونجعلها أذكى.',
  'hero.lede': 'نبني. ندير. نبتكر. ثماني خدمات تحت فريقٍ مرخّصٍ واحد — وجهة مسؤولية واحدة.',
  'cta.enquire': 'ابدأ استفسارك',
  'cta.whatsapp': 'راسلنا على واتساب',
  'cta.call': 'اتصل بنا 7758 509 50 971+',
  'cta.title': 'أخبرنا بما تخطط له.',
  'cta.lede': 'فيلا، برج، سينما منزلية، أو أعمال أذكى — ابدأ الحديث ونحن نتولّى الباقي.',
  'gaps.title': 'معظم المشاريع لا تفشل في الموقع. بل تفشل في الفجوات.',
  'gaps.lede': 'بين المقاول والاستشاري. بين التسليم والتشغيل. وُجدت إنوفا لتغلق هذه الفجوات — فريق واحد مسؤول عن الكل.',
  'orbit.title': 'ماسة واحدة. تسعة أوجه.',
  'orbit.lede': 'كل وجهٍ خدمة — وخلف كل خدمة يجيب الفريق نفسه.',
  'orbit.hint': 'اسحب لتدوير الحلقة · اضغط على أي بوابة للدخول',
  'svc.contracting.name': 'المقاولات بنظام تسليم المفتاح',
  'svc.contracting.short': 'المقاولات',
  'svc.contracting.tag': 'من الهيكل إلى التحفة.',
  'svc.contracting.desc': 'تصميم وبناء وتشطيب بعقدٍ واحد. هيكلٌ خام يتحوّل إلى مساحةٍ جاهزة تعمل — من دون أن تلاحق عشر شركات.',
  'svc.contracting.pack': 'تشطيبات · تجديد · بناء جديد',
  'svc.pm.name': 'إدارة المشاريع',
  'svc.pm.short': 'المشاريع',
  'svc.pm.tag': 'نحن في صفّك.',
  'svc.pm.desc': 'تخطيط وطرح مناقصات وإشراف وتقارير. نمثّل مصلحتك من أول رسمٍ إلى آخر ملاحظة تسليم.',
  'svc.pm.pack': 'ممثل المالك · إدارة التصميم · إشراف على الموقع',
  'svc.facility.name': 'الصيانة وإدارة المرافق',
  'svc.facility.short': 'المرافق',
  'svc.facility.tag': 'مبانٍ لا تنام.',
  'svc.facility.desc': 'صيانة وقائية وطارئة وعناية بالأنظمة الكهروميكانيكية وتشغيل للمرافق يُبقي عقارك بأفضل أداء على مدار الساعة.',
  'svc.facility.pack': 'عقود سنوية · صيانة عند الطلب · تشغيل كامل للمرافق',
  'svc.cinema.name': 'السينما والمسرح المنزلي',
  'svc.cinema.short': 'السينما',
  'svc.cinema.tag': 'عرضك الأول الخاص.',
  'svc.cinema.desc': 'صوتيات وصورة معايَرة ومقاعد وتحكّم — صالات سينما خاصة نصمّمها ونبنيها ونضبطها من البداية إلى النهاية.',
  'svc.cinema.pack': 'غرفة ميديا · سينما مخصّصة · مستوى مرجعي',
  'svc.snagging.name': 'فحص السناجينج',
  'svc.snagging.short': 'السناجينج',
  'svc.snagging.tag': 'نرى ما يفوت الآخرين.',
  'svc.snagging.desc': 'فحوصات استلام مستقلة مع تقرير عيوبٍ يمكن لمطوّرك التعامل معه — قبل أن توقّع.',
  'svc.snagging.pack': 'شقة · فيلا · إعادة فحص',
  'svc.marketing.name': 'التسويق والعلاقات العامة والتواصل',
  'svc.marketing.short': 'التسويق',
  'svc.marketing.tag': 'اجعل اسمك لا يُفوَّت.',
  'svc.marketing.desc': 'علامة ومحتوى وتواصل يحمل اسمك أبعد — يبنيه ويديره فريقٌ واحد مسؤول.',
  'svc.marketing.pack': 'الهوية والعلامة · حملات · تواصل مستمر',
  'svc.consultancy.name': 'الاستشارات الإدارية',
  'svc.consultancy.short': 'الاستشارات',
  'svc.consultancy.tag': 'نظامٌ من التفاصيل المتحركة.',
  'svc.consultancy.desc': 'هيكلة وإجراءات وحوكمة للأعمال النامية — نصائح عملية تصل إلى التشغيل، لا إلى العروض التقديمية فقط.',
  'svc.consultancy.pack': 'تشخيص · نموذج تشغيلي · تنفيذ',
  'svc.ai.name': 'أبحاث واستشارات الذكاء الاصطناعي',
  'svc.ai.short': 'الذكاء الاصطناعي',
  'svc.ai.tag': 'اجعلها أذكى.',
  'svc.ai.desc': 'أبحاث ذكاء اصطناعي تطبيقية وأتمتة واستشارات — نجد أين يوفّر الذكاء وقتك ومالك، ثم نبنيه.',
  'svc.ai.pack': 'جاهزية الذكاء الاصطناعي · مشاريع تجريبية · نشر وتدريب',
  'svc.homewatch.name': 'مراقبة المنازل وكونسيرج العقارات',
  'svc.homewatch.short': 'مراقبة المنازل',
  'svc.homewatch.tag': 'بيتك في عينٍ ساهرة.',
  'svc.homewatch.desc': 'زيارات تفقّد منتظمة وتجهيز للضيوف وخدمات كونسيرج لفيلتك أثناء غيابك. قريباً.',
  'svc.homewatch.pack': 'زيارات مراقبة · تجهيز الوصول · كونسيرج عند الطلب',
  'why.title': 'أطراف أقل. إجابات أوضح.',
  'why.p1.t': 'شريك واحد مسؤول',
  'why.p1.d': 'التصميم والبناء والتشغيل باتفاقية واحدة — مكالمة واحدة حين تحتاج جواباً.',
  'why.p2.t': 'فريق مرخّص متعدد التخصصات',
  'why.p2.d': 'شركة مرخّصة في ميدان، دبي، تضم الحِرف والاختصاصيين داخلياً.',
  'why.p3.t': 'لا تبادل للّوم',
  'why.p3.d': 'حين يملك فريقٌ واحد النطاق كاملاً، لا تجد المشاكل فجوةً تختبئ فيها.',
  'why.p4.t': 'استمرارية',
  'why.p4.d': 'الفريق الذي بنى مساحتك يبقى ليشغّلها ويصونها.',
  'why.p5.t': 'نطاق شفاف',
  'why.p5.d': 'نطاق وجداول وتقارير واضحة — تعرف دائماً أين يقف مشروعك.',
  'why.p6.t': 'أذكى بالتصميم',
  'why.p6.d': 'ذكاء اصطناعي وأتمتة حيث يوفّران لك فعلاً الوقت والمال.',
  'process.title': 'كيف نعمل',
  'process.s1.t': 'نستمع',
  'process.s1.d': 'نبدأ من أهدافك وقيودك وواقع موقعك.',
  'process.s2.t': 'نحدد النطاق',
  'process.s2.d': 'نطاق واضح وجدول زمني ومسؤول واحد — يُتَّفق عليه قبل بدء العمل.',
  'process.s3.t': 'ننفّذ',
  'process.s3.d': 'فرق مرخّصة تنفّذ. مكالمة واحدة، بلا فجوات، بلا مفاجآت.',
  'process.s4.t': 'ندعم',
  'process.s4.d': 'نبقى بعد التسليم — صيانة وعناية وتطوير.',
  'contact.addr': 'ميدان، دبي، الإمارات العربية المتحدة',
  'footer.tag': 'نبني. ندير. نبتكر.',
  'footer.soon': 'مراقبة المنازل وكونسيرج العقارات — قريباً.',
  'sticky.call': 'اتصال',
  'sticky.enquire': 'استفسر',
  'loader.preparing': 'نُجهّز الماسة',
  'loader.enterSound': 'ادخل مع الصوت',
  'loader.enterQuiet': 'ادخل بصمت',
  'world.return': 'عُد إلى الماسة',
  'world.prev': 'الخدمة السابقة',
  'world.next': 'الخدمة التالية',
};

export const MESSAGES: Record<Lang, Dict> = { en, ar };

export function t(lang: Lang, key: string): string {
  return MESSAGES[lang][key] ?? MESSAGES.en[key] ?? key;
}
