/**
 * All editable copy lives here (plus the static English baked into index.html —
 * keep the two in sync when you edit; see README "Editing content").
 *
 * Service copy (taglines, descriptions, offer paragraphs, capabilities,
 * package names) is taken from the live innovagroup.co.ae service pages.
 * Arabic is a faithful translation of that copy — have a native speaker
 * review tone before launch (NOTES.md).
 */

export type Lang = 'en' | 'ar';

export interface ServiceDef {
  id: string;
  /** world scene key rendered when diving through this portal */
  world:
    | 'contracting' | 'pm' | 'facility' | 'cinema' | 'snagging'
    | 'marketing' | 'consultancy' | 'ai' | 'homewatch';
  /** Real service page on innovagroup.co.ae */
  url: string;
  soon?: boolean;
}

export const CONTACT_URL = 'https://innovagroup.co.ae/contact/';
export const WHATSAPP_URL = 'https://wa.me/971505097758';
export const PHONE = '+971505097758';

export const SERVICES: ServiceDef[] = [
  { id: 'contracting', world: 'contracting', url: 'https://innovagroup.co.ae/contracting/' },
  { id: 'pm', world: 'pm', url: 'https://innovagroup.co.ae/project-management/' },
  { id: 'facility', world: 'facility', url: 'https://innovagroup.co.ae/facility-management/' },
  { id: 'cinema', world: 'cinema', url: 'https://innovagroup.co.ae/cinema/' },
  { id: 'snagging', world: 'snagging', url: 'https://innovagroup.co.ae/snagging/' },
  { id: 'marketing', world: 'marketing', url: 'https://innovagroup.co.ae/marketing/' },
  { id: 'consultancy', world: 'consultancy', url: 'https://innovagroup.co.ae/consultancy/' },
  { id: 'ai', world: 'ai', url: 'https://innovagroup.co.ae/ai/' },
  { id: 'homewatch', world: 'homewatch', url: CONTACT_URL, soon: true },
];

type Dict = Record<string, string>;

const en: Dict = {
  'ui.skip': 'Skip to content',
  'ui.sound': 'Sound on/off',
  'aria.home': 'Innova Group — home',
  'ui.menu': 'Menu',
  'ui.scroll': 'Scroll',
  'ui.enterWorld': 'Step inside',
  'ui.explore': 'Full service page',
  'ui.comingSoon': 'Coming soon',
  'ui.notify': 'Ask about launch',
  'ui.capsTitle': 'What we do',
  'ui.packsTitle': 'Packages',
  'ui.service': 'Service',
  'ui.read': 'Explore the full service',
  'ui.close': 'Close',
  'ui.theme': 'Switch between day and night mode',
  'nav.services': 'Services',
  'nav.why': 'Why Innova',
  'nav.process': 'How we work',
  'nav.enquire': 'Enquire',
  'hero.kicker': 'Innova Group LLC · Meydan, Dubai',
  'hero.title': 'We build it, we run it, and we make it smarter.',
  'hero.lede': 'Build. Manage. Innovate. Eight service lines under one licensed team — and one point of accountability.',
  'cta.enquire': 'Start an enquiry',
  'cta.whatsapp': 'WhatsApp us',
  'cta.call': 'Call +971 50 509 7758',
  'cta.title': 'Tell us what you’re planning.',
  'cta.lede': 'Whether it’s a fit-out, a handover inspection, a rebrand or an AI pilot — start with a conversation. No obligation.',
  'gaps.title': 'Most projects don’t fail on site. They fail in the gaps.',
  'gaps.lede': 'Between the designer and the contractor. Between handover and the first year of operation. Between a good product and the market understanding it. Innova Group was built to close those gaps.',
  'orbit.title': 'One diamond. Nine facets.',
  'orbit.lede': 'Every facet is a service — and behind each one, the same team answers.',
  'orbit.hint': 'Drag to spin the ring · click a portal to step inside',
  'svc.contracting.name': 'Turnkey Contracting',
  'svc.contracting.short': 'Contracting',
  'svc.contracting.tag': 'One contract, from empty shell to open doors.',
  'svc.contracting.desc': 'Design, build and hand over under one contract — from empty shell to a completed, tested, ready-to-occupy space.',
  'svc.contracting.offerT': 'The whole build, under one signature',
  'svc.contracting.offer1': 'Splitting a fit-out across a designer, a main contractor, an MEP subcontractor and an AV specialist means four programmes, four invoices and four versions of whose fault it is.',
  'svc.contracting.offer2': 'We take responsibility for design coordination, procurement, construction, services, finishes and commissioning — one programme, one cost plan, one project lead who answers the phone.',
  'svc.contracting.caps': 'Design coordination & authority approvals · Civil, MEP & structural works · Joinery & specialist finishes · AV & smart-home integration · Testing, commissioning & snagging · As-built drawings & warranties',
  'svc.contracting.pack': 'Fit-Out Essential · Turnkey Complete · Design & Build Plus',
  'svc.pm.name': 'Project Management',
  'svc.pm.short': 'Projects',
  'svc.pm.tag': 'Your interests, represented on site.',
  'svc.pm.desc': 'Independent control of programme, cost, quality and risk on your behalf — from brief and tender through to handover.',
  'svc.pm.offerT': 'A professional client-side team, without the headcount',
  'svc.pm.offer1': 'A contractor’s job is to deliver their scope profitably. Somebody has to hold the whole programme, verify what’s been paid for and say no when it matters. That is our role.',
  'svc.pm.offer2': 'From brief to close-out we shape the scope, run the tender, administer the contract, monitor programme and cost, and inspect quality — deliberately independent, never also the contractor.',
  'svc.pm.caps': 'Tender & contractor selection · Contract administration · Programme & critical path · Cost control & change control · Site supervision & quality · Handover & close-out',
  'svc.pm.pack': 'Advisory · Managed Delivery · Programme Office',
  'svc.facility.name': 'Maintenance & Facility Management',
  'svc.facility.short': 'Facility',
  'svc.facility.tag': 'Buildings that keep working after everyone goes home.',
  'svc.facility.desc': 'Planned and reactive maintenance that keeps buildings, systems and occupants running without interruption.',
  'svc.facility.offerT': 'Maintenance as a schedule, not a reaction',
  'svc.facility.offer1': 'Most property problems in this climate are predictable: AC performance, water systems, seals, electrical loads. They become expensive only when nobody is watching the schedule.',
  'svc.facility.offer2': 'We build a maintenance regime around your actual assets — surveyed, listed and given a service interval — then run it to a calendar you can see, with a response team for the times it still happens.',
  'svc.facility.caps': 'Planned preventive maintenance · 24/7 reactive call-out · HVAC, electrical & plumbing · Fire & life-safety compliance · Pools, landscape & civil repairs · Asset register & KPI reporting',
  'svc.facility.pack': 'Care · Care Plus · Integrated FM',
  'svc.cinema.name': 'Cinema & Home Theatre',
  'svc.cinema.short': 'Cinema',
  'svc.cinema.tag': 'A room that disappears, so the film doesn’t.',
  'svc.cinema.desc': 'Private cinemas and media rooms — engineered for acoustics, calibrated for picture, maintained for the long term.',
  'svc.cinema.offerT': 'The room matters more than the equipment',
  'svc.cinema.offer1': 'Expensive speakers in an untreated room sound worse than modest speakers in a treated one. Most disappointing cinemas are a room problem wearing an equipment problem’s clothes.',
  'svc.cinema.offer2': 'We start with the space — dimensions, reflections, sightlines — then specify equipment to suit the room, calibrate picture and sound on completion, and hand over a control system guests can use.',
  'svc.cinema.caps': 'Acoustic analysis & treatment · Dolby Atmos surround design · Projection & screen engineering · Lighting, blackout & automation · Single-remote control · Calibration & ongoing service',
  'svc.cinema.pack': 'Media Room · Dedicated Cinema · Reference Cinema',
  'svc.snagging.name': 'Snagging',
  'svc.snagging.short': 'Snagging',
  'svc.snagging.tag': 'Find it before you sign for it.',
  'svc.snagging.desc': 'Independent pre-handover inspection with a photographic, room-by-room defect report your developer can act on.',
  'svc.snagging.offerT': 'The last moment your leverage is free',
  'svc.snagging.offer1': 'Once you accept handover, defects become a warranty claim: slower, more contested and sometimes at your cost. Before you accept, they are simply the developer’s outstanding work.',
  'svc.snagging.offer2': 'We inspect room by room against finishing standards, record every defect with a photograph and a location, grade it by severity, and issue a register formatted for the developer’s own process. We are paid to find things.',
  'svc.snagging.caps': 'Room-by-room inspection · Thermal imaging & moisture readings · MEP performance testing · Severity-graded photo register · Developer-ready 48h report · Re-inspection & close-out',
  'svc.snagging.pack': 'Standard Snag · Snag & Re-Inspect · Villa & Portfolio',
  'svc.marketing.name': 'Marketing, PR & Communication',
  'svc.marketing.short': 'Marketing',
  'svc.marketing.tag': 'Be understood before you’re chosen.',
  'svc.marketing.desc': 'Brand, campaign and reputation work for companies that need to be understood before they can be chosen.',
  'svc.marketing.offerT': 'Clarity first, volume second',
  'svc.marketing.offer1': 'A great deal of marketing spend goes into saying more, more often, about a proposition nobody has made clear. Volume rarely fixes that.',
  'svc.marketing.offer2': 'We begin with positioning — what you sell, who it is for, why it is different — then run the visible work: content, campaigns and media relations, reported against enquiries and cost per acquisition, not impressions.',
  'svc.marketing.caps': 'Positioning & messaging · Brand identity direction · Social & content production · Paid media & performance · Press & media relations · Crisis & reputation management',
  'svc.marketing.pack': 'Brand Foundation · Always-On · Full Communications',
  'svc.consultancy.name': 'Management Consultancies',
  'svc.consultancy.short': 'Consultancy',
  'svc.consultancy.tag': 'Growth outruns process. We help it catch up.',
  'svc.consultancy.desc': 'Operating models, processes and governance rebuilt so that growth doesn’t outpace control.',
  'svc.consultancy.offerT': 'The company outgrew how it was run',
  'svc.consultancy.offer1': 'Most operational pain in a growing business is not a people problem. It is a structure problem: decisions with no owner, processes that live in someone’s head, and reporting that arrives too late to act on.',
  'svc.consultancy.offer2': 'We diagnose that structure honestly, then rebuild the failing parts — operating model, procedures, delegation, controls, KPIs — and stay through implementation, because an unimplemented report changes nothing.',
  'svc.consultancy.caps': 'Operating model & org design · SOPs & process mapping · Governance & delegation · Financial controls & reporting · KPI dashboards · Change management & coaching',
  'svc.consultancy.pack': 'Diagnostic · Build & Implement · Embedded Advisory',
  'svc.ai.name': 'AI Research & Consultancy',
  'svc.ai.short': 'AI',
  'svc.ai.tag': 'Artificial intelligence, applied where it actually pays.',
  'svc.ai.desc': 'Applied artificial intelligence — where it creates real value in your business, and how to deploy it safely.',
  'svc.ai.offerT': 'Most AI projects fail on the use case, not the technology',
  'svc.ai.offer1': 'The failures we see are almost always upstream: a use case nobody needed, data that was never ready, or a pilot with no definition of success.',
  'svc.ai.offer2': 'We start where your organisation actually spends effort, build one use case properly end-to-end, measure it against agreed criteria, and only scale what earns it — including governance, privacy and the training that gets it adopted.',
  'svc.ai.caps': 'AI opportunity assessment · Document processing & extraction · Workflow automation · Knowledge assistants over your data · Model evaluation & monitoring · Governance, privacy & training',
  'svc.ai.pack': 'AI Readiness · Pilot Build · AI Partner',
  'svc.homewatch.name': 'Home Watch & Property Concierge',
  'svc.homewatch.short': 'Home Watch',
  'svc.homewatch.tag': 'Watched over, always.',
  'svc.homewatch.desc': 'Regular inspections, guest readiness and concierge care for your villa while you’re away. Launching soon.',
  'svc.homewatch.offerT': 'Watched over while you’re away',
  'svc.homewatch.offer1': 'A villa that stands empty still lives: AC cycles, water moves, dust settles, deliveries arrive. Small issues become expensive ones only when nobody is there to notice.',
  'svc.homewatch.offer2': 'Regular documented inspections, guest and arrival preparation, and concierge errands — run by the same team that maintains the property. Launching soon.',
  'svc.homewatch.caps': 'Scheduled property checks · Photographic visit reports · Arrival & guest preparation · Post, plants & pets · Vendor access supervision · Emergency response coordination',
  'svc.homewatch.pack': 'Watch visits · Arrival prep · Concierge on demand',
  'why.title': 'Fewer parties. Clearer answers.',
  'why.p1.t': 'One accountable party',
  'why.p1.d': 'When contracting, management and maintenance sit in the same group, there is nobody left to blame — and nothing left to fall between contracts.',
  'why.p2.t': 'Programme first',
  'why.p2.d': 'Dates are commitments, not aspirations. Every engagement starts with a programme, a cost plan and the reporting rhythm that keeps both honest.',
  'why.p3.t': 'Documented, not remembered',
  'why.p3.d': 'Photographic reports, snag registers, asset lists and O&M records. You keep the evidence, not just the outcome.',
  'why.p4.t': 'Built for what’s next',
  'why.p4.d': 'An in-house AI practice means the systems we hand over are designed to be automated, measured and improved — not replaced in three years.',
  'why.p5.t': 'Rooted in Dubai',
  'why.p5.d': 'A licensed UAE company that knows local authorities, approvals, developer handover standards and the realities of building here.',
  'why.p6.t': 'Scoped in packages',
  'why.p6.d': 'Every discipline is offered in clear packages, quoted against your actual scope — you know what you are engaging before you commit.',
  'process.title': 'How we work',
  'process.s1.t': 'Listen',
  'process.s1.d': 'We start with your goals, constraints and the realities of your site.',
  'process.s2.t': 'Scope',
  'process.s2.d': 'A clear scope, timeline and one accountable owner — agreed before work begins.',
  'process.s3.t': 'Deliver',
  'process.s3.d': 'Licensed teams execute. One call, no gaps, no surprises.',
  'process.s4.t': 'Support',
  'process.s4.d': 'We stay after handover — maintenance, care and upgrades.',
  'contact.addr': 'Meydan, Dubai, United Arab Emirates',
  'footer.tag': 'Build. Manage. Innovate.',
  'footer.soon': 'Home Watch & Property Concierge — coming soon.',
  'sticky.call': 'Call',
  'sticky.enquire': 'Enquire',
  'loader.preparing': 'Preparing the diamond',
  'loader.enter': 'Enter',
  'loader.quiet': 'Enter without sound',
  'world.return': 'Back to the diamond',
  'world.prev': 'Previous service',
  'world.next': 'Next service',
};

const ar: Dict = {
  'ui.skip': 'تخطَّ إلى المحتوى',
  'ui.sound': 'تشغيل/إيقاف الصوت',
  'aria.home': 'إنوفا جروب — الرئيسية',
  'ui.menu': 'القائمة',
  'ui.scroll': 'مرّر',
  'ui.enterWorld': 'ادخل العالم',
  'ui.explore': 'صفحة الخدمة الكاملة',
  'ui.comingSoon': 'قريباً',
  'ui.notify': 'اسأل عن الإطلاق',
  'ui.capsTitle': 'ماذا نقدّم',
  'ui.packsTitle': 'الباقات',
  'ui.service': 'الخدمة',
  'ui.read': 'استكشف الخدمة كاملة',
  'ui.close': 'إغلاق',
  'ui.theme': 'التبديل بين الوضع النهاري والليلي',
  'nav.services': 'خدماتنا',
  'nav.why': 'لماذا إنوفا',
  'nav.process': 'كيف نعمل',
  'nav.enquire': 'استفسر',
  'hero.kicker': 'إنوفا جروب ذ.م.م · ميدان، دبي',
  'hero.title': 'نبنيها، نديرها، ونجعلها أذكى.',
  'hero.lede': 'نبني. ندير. نبتكر. ثماني خدمات تحت فريقٍ مرخّصٍ واحد — وجهة مسؤولية واحدة.',
  'cta.enquire': 'ابدأ استفسارك',
  'cta.whatsapp': 'راسلنا على واتساب',
  'cta.call': 'اتصل بنا 7758 509 50 971+',
  'cta.title': 'أخبرنا بما تخطط له.',
  'cta.lede': 'تشطيبات، فحص استلام، هوية جديدة أو مشروع ذكاء اصطناعي — ابدأ بحديثٍ دون أي التزام.',
  'gaps.title': 'معظم المشاريع لا تفشل في الموقع. بل تفشل في الفجوات.',
  'gaps.lede': 'بين المصمّم والمقاول. بين التسليم وسنة التشغيل الأولى. بين منتجٍ جيد وسوقٍ لم يفهمه بعد. وُجدت إنوفا جروب لتُغلق هذه الفجوات.',
  'orbit.title': 'ماسة واحدة. تسعة أوجه.',
  'orbit.lede': 'كل وجهٍ خدمة — وخلف كل خدمة يجيب الفريق نفسه.',
  'orbit.hint': 'اسحب لتدوير الحلقة · اضغط على أي بوابة للدخول',
  'svc.contracting.name': 'المقاولات بنظام تسليم المفتاح',
  'svc.contracting.short': 'المقاولات',
  'svc.contracting.tag': 'عقدٌ واحد، من هيكلٍ فارغ إلى أبوابٍ مفتوحة.',
  'svc.contracting.desc': 'تصميم وبناء وتسليم بعقدٍ واحد — من هيكلٍ فارغ إلى مساحةٍ مكتملة ومختبَرة وجاهزة للسكن.',
  'svc.contracting.offerT': 'البناء كلّه بتوقيعٍ واحد',
  'svc.contracting.offer1': 'توزيع التشطيب بين مصمّم ومقاولٍ رئيسي ومقاول كهروميكانيك واختصاصي صوتيات يعني أربعة جداول وأربع فواتير وأربع روايات عمّن يقع عليه اللوم.',
  'svc.contracting.offer2': 'نتحمّل مسؤولية تنسيق التصميم والمشتريات والبناء والأنظمة والتشطيبات والتشغيل — جدولٌ واحد، خطة تكلفة واحدة، ومسؤول مشروع واحد يجيب على الهاتف.',
  'svc.contracting.caps': 'تنسيق التصميم وموافقات الجهات · أعمال مدنية وكهروميكانيكية وإنشائية · نجارة وتشطيبات متخصصة · صوتيات ومنزل ذكي · اختبار وتشغيل وفحص · مخططات ما بعد التنفيذ والضمانات',
  'svc.contracting.pack': 'أساسي للتشطيب · تسليم مفتاح كامل · تصميم وبناء بلس',
  'svc.pm.name': 'إدارة المشاريع',
  'svc.pm.short': 'المشاريع',
  'svc.pm.tag': 'مصالحك، ممثَّلة في الموقع.',
  'svc.pm.desc': 'رقابة مستقلة على الجدول والتكلفة والجودة والمخاطر نيابةً عنك — من الموجز والمناقصة حتى التسليم.',
  'svc.pm.offerT': 'فريقٌ محترف في صفّك، دون توظيف',
  'svc.pm.offer1': 'وظيفة المقاول أن ينجز نطاقه بربحية. لكن أحداً يجب أن يمسك الجدول كاملاً، ويتحقق ممّا دُفع مقابله، ويقول «لا» حين يلزم. هذا دورنا.',
  'svc.pm.offer2': 'من الموجز إلى الإقفال: نصوغ النطاق، ندير المناقصة، نراقب الجدول والتكلفة ونفحص الجودة — باستقلالية متعمّدة، فلا نكون نحن المقاول أبداً.',
  'svc.pm.caps': 'المناقصات واختيار المقاول · إدارة العقود · الجدول والمسار الحرج · ضبط التكلفة والتغييرات · إشراف الموقع والجودة · التسليم والإقفال',
  'svc.pm.pack': 'استشاري · تنفيذ مُدار · مكتب برامج',
  'svc.facility.name': 'الصيانة وإدارة المرافق',
  'svc.facility.short': 'المرافق',
  'svc.facility.tag': 'مبانٍ تواصل عملها بعد انصراف الجميع.',
  'svc.facility.desc': 'صيانة وقائية وطارئة تُبقي المباني والأنظمة وقاطنيها في عملٍ متواصل دون انقطاع.',
  'svc.facility.offerT': 'الصيانة جدولٌ زمني، لا ردّة فعل',
  'svc.facility.offer1': 'معظم مشاكل العقارات في هذا المناخ متوقعة: أداء التكييف، أنظمة المياه، العوازل، الأحمال الكهربائية. ولا تصبح مكلفة إلا حين لا يراقب أحدٌ الجدول.',
  'svc.facility.offer2': 'نبني نظام صيانةٍ حول أصولك الفعلية — مسحاً وتسجيلاً وفتراتِ خدمة — ثم نديره وفق تقويمٍ تراه بنفسك، مع فريق استجابة للحالات الطارئة.',
  'svc.facility.caps': 'صيانة وقائية مجدولة · استجابة طوارئ ٢٤/٧ · تكييف وكهرباء وسباكة · سلامة الحريق والامتثال · مسابح وحدائق وإصلاحات مدنية · سجل أصول وتقارير أداء',
  'svc.facility.pack': 'عناية · عناية بلس · إدارة مرافق متكاملة',
  'svc.cinema.name': 'السينما والمسرح المنزلي',
  'svc.cinema.short': 'السينما',
  'svc.cinema.tag': 'غرفة تختفي، كي لا يختفي الفيلم.',
  'svc.cinema.desc': 'صالات سينما خاصة وغرف ميديا — مهندَسة صوتياً، معايَرة الصورة، ومصانة على المدى الطويل.',
  'svc.cinema.offerT': 'الغرفة أهم من المعدّات',
  'svc.cinema.offer1': 'سماعات باهظة في غرفةٍ غير معالجة تبدو أسوأ من سماعات متواضعة في غرفةٍ معالجة. معظم الصالات المخيّبة مشكلة غرفة ترتدي ثياب مشكلة معدّات.',
  'svc.cinema.offer2': 'نبدأ من المساحة — الأبعاد والانعكاسات وخطوط الرؤية — ثم نحدد المعدات لتناسب الغرفة، ونعاير الصورة والصوت عند الإنجاز، ونسلّم نظام تحكم يستطيع الضيوف استخدامه.',
  'svc.cinema.caps': 'تحليل ومعالجة صوتية · تصميم دولبي أتموس · هندسة العرض والشاشة · إضاءة وتعتيم وأتمتة · تحكم بجهاز واحد · معايرة وخدمة مستمرة',
  'svc.cinema.pack': 'غرفة ميديا · سينما مخصصة · سينما مرجعية',
  'svc.snagging.name': 'فحص السناجينج',
  'svc.snagging.short': 'السناجينج',
  'svc.snagging.tag': 'اكتشفه قبل أن توقّع عليه.',
  'svc.snagging.desc': 'فحص مستقل قبل الاستلام مع تقرير عيوبٍ مصوّر، غرفةً بغرفة، يستطيع مطوّرك التعامل معه.',
  'svc.snagging.offerT': 'آخر لحظةٍ تكون فيها قوّتك التفاوضية مجانية',
  'svc.snagging.offer1': 'بعد قبول الاستلام تتحوّل العيوب إلى مطالبة ضمان: أبطأ وأكثر جدلاً وربما على نفقتك. أما قبله، فهي ببساطة أعمالٌ متبقية على المطوّر.',
  'svc.snagging.offer2': 'نفحص غرفةً بغرفة وفق معايير التشطيب، نوثّق كل عيبٍ بصورة وموقع، نصنّفه حسب الخطورة، ونصدر سجلاً بصيغة عمليات المطوّر نفسها. نحن نُدفَع لنجد الأشياء.',
  'svc.snagging.caps': 'فحص غرفة بغرفة · تصوير حراري وقياس رطوبة · اختبار أنظمة كهروميكانيكية · سجل مصوّر مصنّف بالخطورة · تقرير جاهز خلال ٤٨ ساعة · إعادة فحص وإقفال',
  'svc.snagging.pack': 'فحص قياسي · فحص وإعادة فحص · فيلا ومحفظة',
  'svc.marketing.name': 'التسويق والعلاقات العامة والتواصل',
  'svc.marketing.short': 'التسويق',
  'svc.marketing.tag': 'كن مفهوماً قبل أن يقع الاختيار عليك.',
  'svc.marketing.desc': 'أعمال العلامة والحملات والسمعة لشركاتٍ تحتاج أن تُفهَم قبل أن تُختار.',
  'svc.marketing.offerT': 'الوضوح أولاً، والكثافة ثانياً',
  'svc.marketing.offer1': 'قدرٌ كبير من الإنفاق التسويقي يذهب إلى قول المزيد، مراتٍ أكثر، عن عرضٍ لم يوضّحه أحد. والكثافة نادراً ما تصلح ذلك.',
  'svc.marketing.offer2': 'نبدأ من التموضع — ماذا تبيع، لمن، ولماذا أنت مختلف — ثم ندير العمل الظاهر: محتوى وحملات وعلاقات إعلامية، بتقارير تقيس الاستفسارات وكلفة الاستحواذ لا الانطباعات.',
  'svc.marketing.caps': 'تموضع ورسائل · اتجاه الهوية البصرية · محتوى وإدارة قنوات · إعلانات مدفوعة وأداء · علاقات صحفية وإعلامية · إدارة الأزمات والسمعة',
  'svc.marketing.pack': 'أساس العلامة · تشغيل مستمر · تواصل شامل',
  'svc.consultancy.name': 'الاستشارات الإدارية',
  'svc.consultancy.short': 'الاستشارات',
  'svc.consultancy.tag': 'النموّ يسبق الإجراءات. نساعدها على اللحاق.',
  'svc.consultancy.desc': 'نماذج تشغيل وإجراءات وحوكمة يُعاد بناؤها كي لا يتجاوز النموُّ السيطرةَ.',
  'svc.consultancy.offerT': 'الشركة كبرت على طريقة إدارتها',
  'svc.consultancy.offer1': 'معظم الألم التشغيلي في الأعمال النامية ليس مشكلة أشخاص، بل مشكلة هيكل: قرارات بلا مالك، وإجراءات تعيش في رأس أحدهم، وتقارير تصل بعد فوات الأوان.',
  'svc.consultancy.offer2': 'نشخّص ذلك الهيكل بصدق، ثم نعيد بناء الأجزاء المتعثرة — نموذج التشغيل والإجراءات والتفويض والضوابط والمؤشرات — ونبقى حتى التنفيذ، لأن تقريراً غير منفَّذ لا يغيّر شيئاً.',
  'svc.consultancy.caps': 'نموذج التشغيل والهيكلة · إجراءات وخرائط عمليات · حوكمة وتفويض صلاحيات · ضوابط مالية وتقارير · لوحات مؤشرات أداء · إدارة التغيير والتدريب',
  'svc.consultancy.pack': 'تشخيص · بناء وتنفيذ · استشارة ملازمة',
  'svc.ai.name': 'أبحاث واستشارات الذكاء الاصطناعي',
  'svc.ai.short': 'الذكاء الاصطناعي',
  'svc.ai.tag': 'ذكاءٌ اصطناعي يُطبَّق حيث يُجدي فعلاً.',
  'svc.ai.desc': 'ذكاء اصطناعي تطبيقي — أين يصنع قيمةً حقيقية في أعمالك، وكيف يُنشر بأمان.',
  'svc.ai.offerT': 'معظم مشاريع الذكاء الاصطناعي تفشل في حالة الاستخدام لا في التقنية',
  'svc.ai.offer1': 'الإخفاقات التي نراها تحدث دائماً في المنبع: حالة استخدامٍ لا يحتاجها أحد، بيانات لم تكن جاهزة، أو تجربة بلا تعريفٍ للنجاح.',
  'svc.ai.offer2': 'نبدأ حيث يُنفق جهد مؤسستك فعلاً، نبني حالة استخدام واحدة بإتقانٍ من البداية للنهاية، نقيسها وفق معايير متفق عليها، ولا نوسّع إلا ما يستحق — بما في ذلك الحوكمة والخصوصية والتدريب الذي يضمن التبنّي.',
  'svc.ai.caps': 'تقييم فرص الذكاء الاصطناعي · معالجة واستخلاص المستندات · أتمتة سير العمل · مساعد معرفي على بياناتك · تقييم ومراقبة النماذج · حوكمة وخصوصية وتدريب',
  'svc.ai.pack': 'جاهزية الذكاء الاصطناعي · بناء تجريبي · شريك ذكاء اصطناعي',
  'svc.homewatch.name': 'مراقبة المنازل وكونسيرج العقارات',
  'svc.homewatch.short': 'مراقبة المنازل',
  'svc.homewatch.tag': 'بيتك في عينٍ ساهرة.',
  'svc.homewatch.desc': 'زيارات تفقّد منتظمة وتجهيز للضيوف وخدمات كونسيرج لفيلتك أثناء غيابك. قريباً.',
  'svc.homewatch.offerT': 'في عينٍ ساهرة وأنت بعيد',
  'svc.homewatch.offer1': 'الفيلا الخالية تظل حيّة: التكييف يدور، والماء يجري، والغبار يتراكم، والطرود تصل. المشاكل الصغيرة لا تكبر إلا حين لا يلاحظها أحد.',
  'svc.homewatch.offer2': 'زيارات تفقّد موثّقة، وتجهيز للوصول والضيوف، ومهمات كونسيرج — يديرها الفريق نفسه الذي يصون العقار. قريباً.',
  'svc.homewatch.caps': 'زيارات تفقد مجدولة · تقارير مصوّرة لكل زيارة · تجهيز الوصول والضيوف · البريد والنباتات والحيوانات · إشراف على دخول الموردين · تنسيق استجابة الطوارئ',
  'svc.homewatch.pack': 'زيارات مراقبة · تجهيز الوصول · كونسيرج عند الطلب',
  'why.title': 'أطراف أقل. إجابات أوضح.',
  'why.p1.t': 'جهة واحدة مسؤولة',
  'why.p1.d': 'حين تجتمع المقاولات والإدارة والصيانة في المجموعة نفسها، لا يبقى أحدٌ لتوجيه اللوم إليه — ولا شيء يسقط بين العقود.',
  'why.p2.t': 'الجدول أولاً',
  'why.p2.d': 'المواعيد التزامات لا تمنّيات. كل تعاقد يبدأ بجدولٍ وخطة تكلفة وإيقاع تقارير يُبقيهما صادقَين.',
  'why.p3.t': 'موثَّق لا مَحفوظ في الذاكرة',
  'why.p3.d': 'تقارير مصوّرة وسجلات عيوب وقوائم أصول ووثائق تشغيل وصيانة. تحتفظ بالدليل، لا بالنتيجة فقط.',
  'why.p4.t': 'مبنيّ لما هو قادم',
  'why.p4.d': 'وجود ممارسة ذكاء اصطناعي داخلية يعني أنظمةً تُسلَّم قابلةً للأتمتة والقياس والتحسين — لا للاستبدال بعد ثلاث سنوات.',
  'why.p5.t': 'متجذّرون في دبي',
  'why.p5.d': 'شركة إماراتية مرخّصة تعرف الجهات المحلية والموافقات ومعايير تسليم المطوّرين وواقع البناء هنا.',
  'why.p6.t': 'نطاق في باقات',
  'why.p6.d': 'كل خدمة تُقدَّم في باقاتٍ واضحة تُسعَّر وفق نطاقك الفعلي — تعرف ما تتعاقد عليه قبل أن تلتزم.',
  'process.title': 'كيف نعمل',
  'process.s1.t': 'نستمع',
  'process.s1.d': 'نبدأ من أهدافك وقيودك وواقع موقعك.',
  'process.s2.t': 'نحدد النطاق',
  'process.s2.d': 'نطاق واضح وجدول زمني ومسؤول واحد — يُتَّفق عليه قبل بدء العمل.',
  'process.s3.t': 'ننفّذ',
  'process.s3.d': 'فرق مرخّصة تنفّذ. مكالمة واحدة، بلا فجوات، بلا مفاجآت.',
  'process.s4.t': 'ندعم',
  'process.s4.d': 'نبقى بعد التسليم — صيانة وعناية وتطوير.',
  'contact.addr': 'ميدان، دبي، الإمارات العربية المتحدة',
  'footer.tag': 'نبني. ندير. نبتكر.',
  'footer.soon': 'مراقبة المنازل وكونسيرج العقارات — قريباً.',
  'sticky.call': 'اتصال',
  'sticky.enquire': 'استفسر',
  'loader.preparing': 'نُجهّز الماسة',
  'loader.enter': 'ادخل',
  'loader.quiet': 'ادخل بدون صوت',
  'world.return': 'عُد إلى الماسة',
  'world.prev': 'الخدمة السابقة',
  'world.next': 'الخدمة التالية',
};

export const MESSAGES: Record<Lang, Dict> = { en, ar };

export function t(lang: Lang, key: string): string {
  return MESSAGES[lang][key] ?? MESSAGES.en[key] ?? key;
}